apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases/manila
patches:
- patch: |-
    - op: replace
      path: /spec/secret
      value: osp-secret
    - op: replace
      path: /metadata/namespace
      value: manila-kuttl-tests
  target:
    kind: Manila
- path: tls.yaml
